- greeting:
    text_size: 2xl
    text: "Henrik's Lab"

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
    locale: sv

- resources:
    cpu: true
    memory: true
    disk: /
    label: Raspberry Pi
    expanded: true
    units: metric

- search:
    provider: duckduckgo
    target: _blank
    focus: false
